<div class='tabs'>

  <ul>
    <li id='properties'><a>Свойства</a></li>
  </ul>

  <div id="tab_properties">
    
      
        <dl class="field">
          <dt>{{label for="title"}}title:{{/label}}</dt>
          <dd>{{input id="title" name="title" type="text" title="title"/}}</dd>
        </dl>
      
        <dl class="field">
          <dt>{{label for="description"}}description:{{/label}}</dt>
          <dd>{{textarea id="description" name="description" type="text" title="description" cols="40" rows="7"/}}</dd>
        </dl>
      
        <dl class="field">
          <dt>{{label for="content"}}content:{{/label}}</dt>
          <dd>{{wysiwyg id="content" name="content" width="100%" height="300px" title="content"/}}</dd>
        </dl>
      
    
  </div>

</div>